In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow import keras

In [2]:
(x_train,y_train),(x_test,y_test) = keras.datasets.cifar10.load_data()

In [3]:
x_train.shape

(50000, 32, 32, 3)

In [4]:
y_train

array([[6],
       [9],
       [9],
       ...,
       [9],
       [1],
       [1]], dtype=uint8)

In [5]:
 x_train_scaled = x_train/255
 x_test_scaled = x_test/255

In [14]:
y_train_catrgorical = keras.utils.to_categorical(y_train, num_classes=10,dtype='float32')
y_test_catrgorical = keras.utils.to_categorical(y_test, num_classes=10,dtype='float32')

In [7]:
y_train_catrgorical[:5]

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [8]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape = (32,32,3)),
    keras.layers.Dense(3000, activation='relu'),
    keras.layers.Dense(1000, activation='relu'),
    keras.layers.Dense(10, activation='sigmoid')
])

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 3072)              0         
_________________________________________________________________
dense (Dense)                (None, 3000)              9219000   
_________________________________________________________________
dense_1 (Dense)              (None, 1000)              3001000   
_________________________________________________________________
dense_2 (Dense)              (None, 10)                10010     
Total params: 12,230,010
Trainable params: 12,230,010
Non-trainable params: 0
_________________________________________________________________


In [10]:
model.compile(optimizer='SGD',loss='categorical_crossentropy',metrics=['accuracy'])
model.fit(x_train_scaled,y_train_catrgorical,epochs=50)

Epoch 1/50
1563/1563 [==============================] - 6s 3ms/step - loss: 1.9273 - accuracy: 0.3051
Epoch 2/50
1563/1563 [==============================] - 5s 3ms/step - loss: 1.6390 - accuracy: 0.4215
Epoch 3/50
1563/1563 [==============================] - 5s 3ms/step - loss: 1.5456 - accuracy: 0.4544
Epoch 4/50
1563/1563 [==============================] - 5s 3ms/step - loss: 1.4963 - accuracy: 0.4753
Epoch 5/50
1563/1563 [==============================] - 5s 3ms/step - loss: 1.4353 - accuracy: 0.4921
Epoch 6/50
1563/1563 [==============================] - 5s 3ms/step - loss: 1.3922 - accuracy: 0.5098
Epoch 7/50
1563/1563 [==============================] - 5s 3ms/step - loss: 1.3501 - accuracy: 0.5239
Epoch 8/50
1563/1563 [==============================] - 5s 3ms/step - loss: 1.3143 - accuracy: 0.5393
Epoch 9/50
1563/1563 [==============================] - 5s 3ms/step - loss: 1.2904 - accuracy: 0.5455
Epoch 10/50
1563/1563 [==============================] - 5s 3ms/step - loss: 1.250

In [11]:
model.predict(x_test_scaled)

array([[8.5806155e-01, 5.8053356e-01, 9.1851640e-01, ..., 2.0509821e-04,
        7.1652228e-01, 1.0263020e-01],
       [9.9196315e-01, 9.8623973e-01, 4.2402111e-02, ..., 7.1904874e-01,
        9.9993849e-01, 9.7622097e-01],
       [9.9951565e-01, 9.7510397e-01, 2.6602954e-01, ..., 9.2429972e-01,
        9.9858958e-01, 9.0216297e-01],
       ...,
       [7.8208452e-01, 6.8209809e-04, 9.9729353e-01, ..., 5.5507153e-01,
        3.1762233e-01, 2.1599304e-02],
       [7.6920301e-01, 1.5063699e-01, 9.8992074e-01, ..., 3.0465928e-01,
        2.9991541e-02, 6.7909765e-03],
       [3.6123338e-01, 9.7338222e-02, 9.5839840e-01, ..., 9.6955609e-01,
        2.2360842e-01, 3.7051108e-01]], dtype=float32)

In [15]:
model.evaluate(x_test_scaled,y_test_catrgorical)

313/313 [==============================] - 1s 3ms/step - loss: 1.6079 - accuracy: 0.5491


[1.6078855991363525, 0.5490999817848206]